"""
Excel → MD converter
Usage: python postman/test-cases/convert.py
"""

import openpyxl
from pathlib import Path

BASE = Path(__file__).parent

def convert(xlsx_name):
    xlsx_path = BASE / xlsx_name
    md_path = BASE / xlsx_name.replace(".xlsx", ".md")

    wb = openpyxl.load_workbook(xlsx_path)
    ws = wb.active
    rows = list(ws.iter_rows(values_only=True))
    data = rows[1:]

    folders = {}
    for row in data:
        folder = row[1]
        if folder not in folders:
            folders[folder] = []
        folders[folder].append(row)

    lines = []
    lines.append(f"# {xlsx_name.replace('-tests.xlsx', '').title()} API Test Cases\n")
    lines.append("> **Auto-generated — DO NOT edit this file directly.**")
    lines.append("> If you edit " + xlsx_name + ", run: `python postman/test-cases/convert.py`\n")

    for folder, folder_rows in folders.items():
        lines.append(f"\n## {folder}\n")
        lines.append("| TC | Request Name | Method | Endpoint | Auth | Body (JSON) | Expected Status | Key Assertions | Saves Variable |")
        lines.append("|---|---|---|---|---|---|---|---|---|")
        for row in folder_rows:
            tc, _, name, method, endpoint, auth, body, status, assertions, saves = row
            body = body if body and body != "-" else "-"
            lines.append(f"| {tc} | {name} | {method} | {endpoint} | {auth} | {body} | {status} | {assertions} | {saves} |")

    md_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Done: {md_path.name} updated")

if __name__ == "__main__":
    for xlsx in BASE.glob("*-tests.xlsx"):
        if not xlsx.name.startswith("~$"):
            convert(xlsx.name)
